// <auto-generated />
using System;
using DrawIt.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DrawIt.Models.Migrations
{
    [DbContext(typeof(DrawItAPIContext))]
    partial class DrawItAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DrawIt.Models.Data.Word", b =>
                {
                    b.Property<Guid>("wordId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DNGuessed");

                    b.Property<int>("Guessed");

                    b.Property<int>("dislikes");

                    b.Property<int>("likes");

                    b.Property<string>("wordEng");

                    b.Property<string>("wordNl");

                    b.HasKey("wordId");

                    b.ToTable("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
